#!/usr/bin/env python

import os
import shutil
from transformers import Pix2StructForConditionalGeneration, Pix2StructProcessor

CACHE_DIR = 'model-cache'

if os.path.exists(CACHE_DIR):
    shutil.rmtree(CACHE_DIR)

os.makedirs(CACHE_DIR)


model_urls = {
    "textcaps": "google/pix2struct-textcaps-large", # Finetuned on TextCaps
    "screen2words": "google/pix2struct-screen2words-large", # Finetuned on Screen2Words
    "widgetcaption": "google/pix2struct-widget-captioning-large", # Finetuned on Widget Captioning (captioning a UI component on a screen)
    "infographics": "google/pix2struct-infographics-vqa-large", # Infographics
    "docvqa": "google/pix2struct-docvqa-large", # Visual question answering
    "ai2d": "google/pix2struct-ai2d-large", # Scienfic diagram
}

for model, model_path in model_urls.items():
    processor = Pix2StructProcessor.from_pretrained(model_path, cache_dir=CACHE_DIR)
    model = Pix2StructForConditionalGeneration.from_pretrained(model_path, cache_dir=CACHE_DIR)
